Cargo.toml: Exclude regex/record
It causes the build to fail with:

    # Build the NSS library
    /usr/share/cargo/bin/cargo build --release
    debian cargo wrapper: options, profiles, parallel, lto: ['parallel=4'] ['noudeb'] ['-j4'] 0
    debian cargo wrapper: rust_type, gnu_type: x86_64-unknown-linux-gnu, x86_64-linux-gnu
    debian cargo wrapper: unsetting RUSTFLAGS and assuming it will be (or already was) added to $CARGO_HOME/config.toml
    debian cargo wrapper: running subprocess (['env', 'RUST_BACKTRACE=1', '/usr/bin/cargo', '-Zavoid-dev-deps', 'build', '--verbose', '--verbose', '-j4', '--target', 'x86_64-unknown-linux-gnu', '--release'],) {}
    error: failed to calculate checksum of: /home/runner/work/authd/authd/tmp.gEeEThPKrv/source/vendor_rust/regex/record/old-bench-log/.gitignore

    Caused by:
      failed to open file `/home/runner/work/authd/authd/tmp.gEeEThPKrv/source/vendor_rust/regex/record/old-bench-log/.gitignore`

    Caused by:
      No such file or directory (os error 2)

even though we already exclude .gitignore. Anyway, there doesn't seem to
be anything relevant to the build in there, according to the README.md
it's 'various recordings of results', so let's exclude it entirely.