ci: Fix OCI artifact cleanup
The jobs failed with:

    Error: get versions API failed. Package not found.

That's because the package-name input should not include the name of the
registry and the owner.