chore(lint): Fix nolintlint errors for gosec
Upgrading to 2.12.1 caused the linter to fail with these errors

"""
Running [/home/runner/golangci-lint-2.12.1-linux-amd64/golangci-lint config path] in [/home/runner/work/authd/authd/authd-oidc-brokers] ...
  Running [/home/runner/golangci-lint-2.12.1-linux-amd64/golangci-lint config verify] in [/home/runner/work/authd/authd/authd-oidc-brokers] ...
  Running [/home/runner/golangci-lint-2.12.1-linux-amd64/golangci-lint run --path-mode=abs --config .golangci.yaml --build-tags=withmsentraid] in [/home/runner/work/authd/authd/authd-oidc-brokers] ...
  Error: /home/runner/work/authd/authd/authd-oidc-brokers/internal/providers/msentraid/msmock_test.go:140:2: directive `//nolint:gosec // G120 - test mock server, no untrusted input.` is unused for linter "gosec" (nolintlint)
  	//nolint:gosec // G120 - test mock server, no untrusted input.
  	^
  Error: /home/runner/work/authd/authd/authd-oidc-brokers/internal/testutils/provider.go:219:3: directive `//nolint:gosec // G120 - test-only mock handler; request bodies are controlled by tests.` is unused for linter "gosec" (nolintlint)
  		//nolint:gosec // G120 - test-only mock handler; request bodies are controlled by tests.
  		^
  2 issues:
  * nolintlint: 2

  Error: issues found
"""