ci: Fix invalid cross-device link while moving coverage data
Go tests failed in CI with:

    Error Trace:        /home/runner/work/authd/authd/pam/integration-tests/modulehelpers_test.go:111
                                                /opt/hostedtoolcache/go/1.25.11/x64/src/testing/testing.go:1308
                                                /opt/hostedtoolcache/go/1.25.11/x64/src/testing/testing.go:1572
                                                /opt/hostedtoolcache/go/1.25.11/x64/src/testing/testing.go:1898
    Error:              Received unexpected error:
                        rename /tmp/TestCLIChangeAuthTok1077107872/002/pam_authd_exectestclichangeauthtok.so-module.gcda /home/runner/work/authd/authd/raw-coverage/TestCLIChangeAuthTok.gcov/pam_authd_exectestclichangeauthtok.so-module.gcda: invalid cross-device link
    Test:               TestCLIChangeAuthTok
    Messages:           Teardown: Can't move coverage report data for c Library: rename /tmp/TestCLIChangeAuthTok1077107872/002/

The fix is to move the coverage data from a directory below /tmp to
another directory below /tmp, avoiding crossing filesystem boundaries.

In contrast to the project directory, the directory below /tmp is not
bind-mounted into the LXD containers, so we need to create it there
first for the tests running in LXD containers.

Co-authored-by: Copilot <223556219+Copilot@users.noreply.github.com>