ci: Fix setup-oras action used before checkout
That caused jobs to fail with:

    Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/authd/authd/.github/actions/setup-oras'. Did you forget to run actions/checkout before running your local action?