Cargo.toml: Exclude files which cause build failures
Since a few days, the build of the Debian binary package targeting
Resolute fails with:

    # Build the NSS library
    /usr/share/cargo/bin/cargo build --release
    debian cargo wrapper: options, profiles, parallel, lto: ['parallel=4'] ['noudeb'] ['-j4'] 0
    debian cargo wrapper: rust_type, gnu_type: x86_64-unknown-linux-gnu, x86_64-linux-gnu
    debian cargo wrapper: unsetting RUSTFLAGS and assuming it will be (or already was) added to $CARGO_HOME/config.toml
    debian cargo wrapper: running subprocess (['env', 'RUST_BACKTRACE=1', '/usr/bin/cargo', '-Zavoid-dev-deps', 'build', '--verbose', '--verbose', '-j4', '--target', 'x86_64-unknown-linux-gnu', '--release'],) {}
    error: failed to calculate checksum of: /home/runner/work/authd/authd/tmp.fdIwdqn7lP/source/vendor_rust/ctor/Cargo.toml.orig

    Caused by:
      failed to open file `/home/runner/work/authd/authd/tmp.fdIwdqn7lP/source/vendor_rust/ctor/Cargo.toml.orig`

    Caused by:
      No such file or directory (os error 2)

I spent a considerable amount of time trying to figure out what is
causing this, but I couldn't figure it out. Things I investigated:
* The ctor dependency was not updated (Cargo.toml and Cargo.lock were
  not changed in weeks).
* It's not caused by different cargo or cargo-vendor-filterer versions
  being used when building the source and binary packages.
* I found no recent changes in the source code of `cargo vendor` or
  cargo-vendor-filterer which would cause that.

The only solution I found is to exclude the file in Cargo.toml. After
doing that, the build failed a few more times because other vendored
files were also missing. I also excluded those.