debian/source/options: Don't exclude files from vendor_rust
Excluding files from vendor_rust from the source package causes build
failures because cargo creates a checksum file with all the files. If
any of those are missing when we try to build the NSS module as part of
the binary package, Cargo fails with an error like this:

    # Build the NSS library
    /usr/share/cargo/bin/cargo build --release
    debian cargo wrapper: options, profiles, parallel, lto: ['parallel=4'] ['noudeb'] ['-j4'] 0
    debian cargo wrapper: rust_type, gnu_type: x86_64-unknown-linux-gnu, x86_64-linux-gnu
    debian cargo wrapper: unsetting RUSTFLAGS and assuming it will be (or already was) added to $CARGO_HOME/config.toml
    debian cargo wrapper: running subprocess (['env', 'RUST_BACKTRACE=1', '/usr/bin/cargo', '-Zavoid-dev-deps', 'build', '--verbose', '--verbose', '-j4', '--target', 'x86_64-unknown-linux-gnu', '--release'],) {}
    error: failed to calculate checksum of: /home/runner/work/authd/authd/tmp.QvkZiarXpe/source/vendor_rust/hyper-util/.github/workflows/CI.yml

    Caused by:
      failed to open file `/home/runner/work/authd/authd/tmp.QvkZiarXpe/source/vendor_rust/hyper-util/.github/workflows/CI.yml`

    Caused by:
      No such file or directory (os error 2)

This is happening on Resolute because it now has Cargo 1.92.0 which
doesn't exclude hidden directories from vendored dependencies anymore:

    https://github.com/rust-lang/cargo/commit/e8534d0bc2eb7b6252bf658751345cd950b94392

The solution is to not let dpkg-source exclude any files or directories
from vendor_rust which were not already excluded by `cargo vendor` or
cargo-vendor-filterer. We instead exclude files from the authd project
root and from the Go vendored dependencies in vendor/.

We keep

    tar-ignore = *.a
    tar-ignore = *.o
    tar-ignore = *.so

to make sure that we don't include any unwanted build artifacts in the
source package. If there are any below vendor_rust, that will still
cause the build to fail, but we want that in that case so that we can
manually exclude those fails via cargo-vendor-filterer.