snap: install cargo-c with --locked
Building the authd-msentraid broker started failing with

    error: failed to compile `cargo-c v0.10.23+cargo-0.97.1`, intermediate artifacts can be found at `/root/.cache/authd-oidc-brokers/cargo-target`.
    To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
    Caused by:
      rustc 1.94.0 is not supported by the following package:
        cargo-credential-libsecret@0.5.8 requires rustc 1.95
      Try re-running `cargo install` with `--locked`

Similarly to the previous commit, we now use `cargo install` with
`--locked`.