Cargo.toml: Exclude Cargo.toml.orig file from vendored dirs
Resolute now has Cargo 0.92.0 which doesn't exclude files ending with
".orig" anymore:

    https://github.com/rust-lang/cargo/commit/29ecb7f36a963bed4729bd6909200b4302a366a5

This is causing the build of the Debian binary package targeting
Resolute to fail with:

    # Build the NSS library
    /usr/share/cargo/bin/cargo build --release
    debian cargo wrapper: options, profiles, parallel, lto: ['parallel=4'] ['noudeb'] ['-j4'] 0
    debian cargo wrapper: rust_type, gnu_type: x86_64-unknown-linux-gnu, x86_64-linux-gnu
    debian cargo wrapper: unsetting RUSTFLAGS and assuming it will be (or already was) added to $CARGO_HOME/config.toml
    debian cargo wrapper: running subprocess (['env', 'RUST_BACKTRACE=1', '/usr/bin/cargo', '-Zavoid-dev-deps', 'build', '--verbose', '--verbose', '-j4', '--target', 'x86_64-unknown-linux-gnu', '--release'],) {}
    error: failed to calculate checksum of: /home/runner/work/authd/authd/tmp.fdIwdqn7lP/source/vendor_rust/ctor/Cargo.toml.orig

    Caused by:
      failed to open file `/home/runner/work/authd/authd/tmp.fdIwdqn7lP/source/vendor_rust/ctor/Cargo.toml.orig`

    Caused by:
      No such file or directory (os error 2)

Something is causing the Cargo.toml.orig file to not be included in the
source tarball. I couldn't figure out why that is. The main suspect is
dpkg-source which filters out files from the source tarball based on the
tar-ignore patterns we specify in debian/source/options and some default
patterns. With dpkg-source 1.22.21ubuntu9 those are (from dpkg-source
--help):

  -I, --tar-ignore[=<pattern>]
      filter out files when building tarballs
        (defaults to: -I*.a -I*.la -I*.o -I*.so -I.*.sw? -I*/*~ -I,,* -I.[#~]* -I.arch-ids -I.arch-inventory -I.be -I.bzr -I.bzr.backup -I.bzr.tags -I.bzrignore -I.cvsignore -I.deps -I.git -I.gitattributes -I.gitignore -I.gitmodules -I.gitreview -I.hg -I.hgignore -I.hgsigs -I.hgtags -I.mailmap -I.mtn-ignore -I.shelf -I.svn -ICVS -IDEADJOE -IRCS -I_MTN -I_darcs -I{arch}).

However, none of these match Cargo.toml.orig, so it remains a mystery
why that is excluded from the tarball.

In any case, the fix is to explicitly exclude Cargo.toml.orig via
cargo-vendor-filterer, so that it's excluded from the checksum file.