Cargo.toml: Exclude files which cause build failures
Since a few days, the build of the Debian binary package targeting
Resolute fails with:

    # Build the NSS library
    /usr/share/cargo/bin/cargo build --release
    debian cargo wrapper: options, profiles, parallel, lto: ['parallel=4'] ['noudeb'] ['-j4'] 0
    debian cargo wrapper: rust_type, gnu_type: x86_64-unknown-linux-gnu, x86_64-linux-gnu
    debian cargo wrapper: unsetting RUSTFLAGS and assuming it will be (or already was) added to $CARGO_HOME/config.toml
    debian cargo wrapper: running subprocess (['env', 'RUST_BACKTRACE=1', '/usr/bin/cargo', '-Zavoid-dev-deps', 'build', '--verbose', '--verbose', '-j4', '--target', 'x86_64-unknown-linux-gnu', '--release'],) {}
    error: failed to calculate checksum of: /home/runner/work/authd/authd/tmp.fdIwdqn7lP/source/vendor_rust/ctor/Cargo.toml.orig

    Caused by:
      failed to open file `/home/runner/work/authd/authd/tmp.fdIwdqn7lP/source/vendor_rust/ctor/Cargo.toml.orig`

    Caused by:
      No such file or directory (os error 2)

Something is causing the Cargo.toml.orig file to not be included in the
source tarball. I couldn't figure out what exactly is causing that. The
solution is to let cargo-vendor-filterer exclude the file, so that it's
also excluded from the checksum file.

After doing that, the build failed a few more times because other
vendored files were also missing from the tarball. Those were all
excluded by the tar-ignore options in debian/source/options. The fix is
again to also let cargo-vendor-filterer exclude those.

Note that dpkg-source excludes some patterns with tar-ignore by default.
With dpkg-source 1.22.21ubuntu9 that is (from dpkg-source --help):

  -I, --tar-ignore[=<pattern>]
      filter out files when building tarballs
        (defaults to: -I*.a -I*.la -I*.o -I*.so -I.*.sw? -I*/*~ -I,,* -I.[#~]* -I.arch-ids -I.arch-inventory -I.be -I.bzr -I.bzr.backup -I.bzr.tags -I.bzrignore -I.cvsignore -I.deps -I.git -I.gitattributes -I.gitignore -I.gitmodules -I.gitreview -I.hg -I.hgignore -I.hgsigs -I.hgtags -I.mailmap -I.mtn-ignore -I.shelf -I.svn -ICVS -IDEADJOE -IRCS -I_MTN -I_darcs -I{arch}).

However, none of these match Cargo.toml.orig, so we still don't have an
explanation to why that is excluded from the tarball.